bnbc_upload:
    uniqid: true
    max_file_size: 10485760
    accept_file_types: '/\.(stl)$/i'
    upload_folder: 'uploads/test'
    # image_versions:
    #     thumbnail:
    #         max_width: 100
    #         max_height: 100
    #         crop: true
    #     medium:
    #         max_width: 300
    #         max_height: 300
    #         crop: false
    #     large:
    #         max_width: 1024
    #         max_height: 768
    #         crop: false