
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: CoreBundle\Entity\User
    registration:
      confirmation:
        enabled: true
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_from%"